#!/bin/bash
#
# aoserv-ipreputation - Daemon that feeds IP reputation into the AOServ Platform.
# Copyright (C) 2012, 2020, 2021, 2022  AO Industries, Inc.
#     support@aoindustries.com
#     7262 Bull Pen Cir
#     Mobile, AL 36695
#
# This file is part of aoserv-ipreputation.
#
# aoserv-ipreputation is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# aoserv-ipreputation is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with aoserv-ipreputation.  If not, see <https://www.gnu.org/licenses/>.
#

#
#       /etc/init.d/ipreputation
#
# Starts the IP Reputation Daemon
#
# chkconfig: - 98 02
# description: ipreputation

RETVAL=0

BIN='/opt/ipreputation'
VAR='/var/opt/ipreputation'
PID='/var/run/ipreputation.pid'

#
#       See how we were called.
#
case "$1" in
  start)
        # Check if already running
        if [ ! -f "$PID" ]; then
            echo -n "Starting ipreputation: "
      cd "$BIN"
      nohup \
    su \
    -s /bin/sh \
    -c "exec java -classpath classes:conf:lib/ao-hodgepodge.jar:lib/aoserv-client.jar:lib/ipreputation.jar com.aoindustries.ipreputation.IpReputationDaemon" \
    ipreputation \
    >& "$VAR/ipreputation.log" &
      echo "$!" > "$PID"
      echo "Done"
        fi
        ;;
  stop)
        if [ -f "$PID" ]; then
            echo -n "Stopping ipreputation: "
      kill `cat "$PID"`
            rm -f "$PID"
      echo "Done"
        fi
        ;;
  reload|restart)
        "$0" stop
        "$0" start
        RETVAL=$?
        ;;
  *)
        echo "Usage: /etc/init.d/ipreputation {start|stop|restart|reload}"
        exit 1
esac

exit $RETVAL
